
server:
  port: 8000

pages:
  - page: helldivers,
    buttons: 
      - button: b_1,
        name: test,
        type: keyboard,
        url: https://www.reddit.com/r/kde/comments/fen7lj/plasmoid_for_managing_docker_containers/,
        action: 
          - 0x31
          - 0x31
      - button: b_2,
        name: test,
        type: keyboard,
        url: https://www.reddit.com/r/kde/comments/fen7lj/plasmoid_for_managing_docker_containers/,
        action: 
          - 0x31
          - 0x31
  - page: media,
    buttons: 
      - button: b_1,
        name: test,
        type: keyboard,
        url: https://www.reddit.com/,
        action: 
          - 0x31
          - 0x31