
server:
  port: 8000

pages:
  - page: helldivers
    buttons: 
      - button: reinforce
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: "reinforce"
        
      - button: flamethrower
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: "flamethrower"

      - button: anti-material
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: "anti-material"

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: strafing-run
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: strafing-run

      - button: airstrike
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: airstrike
      
      - button: cluster-bomb
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: cluster-bomb
      
      - button: napalm-airstrike
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: napalm-airstrike
        
      - button: smoke-strike
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: smoke-strike
        
      - button: rocket-pods
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: rocket-pods
        
      - button: bomb
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: bomb

      - button: full-screen
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "full-screen"
          - name: Color
            value: orange

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: orange

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: orbital-380-barrage
        function: HelldiversTwoMacro
        parameters:
          - name: Key
            value: orbital-380-barrage

      - button: page
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "set-page"
          - name: PageId
            value: "media"
          - name: Image
            value: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdEjIsQcn8NwYWhwISL74xXLGtRHeW1Mn67g&s"


  - page: media
    buttons: 
      - button: mute
        function: MediaMacro
        parameters:
          - name: Key
            value: "mute"

      - button: mute
        function: MediaMacro
        parameters:
          - name: Key
            value: "previous"

      - button: mute
        function: MediaMacro
        parameters:
          - name: Key
            value: "play/pause"

      - button: mute
        function: MediaMacro
        parameters:
          - name: Key
            value: "next"
      
      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "full-screen"
          - name: Color
            value: orange
      
      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red

      - button: spacer
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "spacer"
          - name: Color
            value: red
      - button: page
        function: FakeDeckMacro
        parameters:
          - name: Key
            value: "set-page"
          - name: PageId
            value: "helldivers"
          - name: Image
            value: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2oyk6yqmBxt9ejwqBaordr6X9s-dZFnHrvg&s"